const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('betterboard', {
  platform: process.platform,
  autosave: (json) => ipcRenderer.invoke('board:autosave', json),
  loadAutosave: () => ipcRenderer.invoke('board:load-autosave'),
  saveBoard: (json) => ipcRenderer.invoke('board:save', json),
  openBoard: () => ipcRenderer.invoke('board:open'),
  openImages: () => ipcRenderer.invoke('image:open'),
  clipboardImage: () => ipcRenderer.invoke('clipboard:image'),
  clipboardText: () => ipcRenderer.invoke('clipboard:text'),
  clipboardWriteImage: (dataURL, text) => ipcRenderer.invoke('clipboard:write-image', dataURL, text),
  clipboardWriteText: (text) => ipcRenderer.invoke('clipboard:write-text', text),
  loadStickers: () => ipcRenderer.invoke('stickers:load'),
  saveStickers: (stickers) => ipcRenderer.invoke('stickers:save', stickers),
  exportPNG: (dataURL) => ipcRenderer.invoke('board:export-png', dataURL),
  exportAnimation: (bytes, format) => ipcRenderer.invoke('board:export-animation', bytes, format),
  confirm: (message, detail) => ipcRenderer.invoke('ui:confirm', message, detail),
  onMenu: (cb) => ipcRenderer.on('menu', (_e, action) => cb(action)),

  aiConnections: () => ipcRenderer.invoke('ai:connections'),
  aiLocalProviders: () => ipcRenderer.invoke('ai:local-providers'),
  aiSaveConnection: (connection) => ipcRenderer.invoke('ai:save-connection', connection),
  aiSetActive: (id) => ipcRenderer.invoke('ai:set-active', id),
  aiDeleteConnection: (id) => ipcRenderer.invoke('ai:delete-connection', id),
  aiAsk: (payload) => ipcRenderer.invoke('ai:ask', payload),
  aiCancel: () => ipcRenderer.invoke('ai:cancel'),
  onAiDelta: (cb) => ipcRenderer.on('ai:delta', (_e, text) => cb(text)),
  onAiDone: (cb) => ipcRenderer.on('ai:done', () => cb()),
  onAiError: (cb) => ipcRenderer.on('ai:error', (_e, message) => cb(message)),
  onAiDraw: (cb) => ipcRenderer.on('ai:draw', (_e, payload) => cb(payload)),
});
